openapi: 3.0.0
info:
  title: WEB-Calendar API
  version: 1.0.0
  description: API for WEB-Calendar

servers:
 - url: /api

components:
  schemas:
    Event:
      type: object
      required:
        - description_of_event
      properties:
        description_of_event:
          type: string
  parameters:
    description_of_event:
      name: description_of_event
      in: path
      required: true
      schema:
        type: string

paths:
  /events:
    get:
      summary: Get lisf of all events
      tags:
        - Events
      operationId: events.get_all_events
      responses:
        '200':
          description: Successfully read all events
